<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_110201  Bank</name>
   <tag></tag>
   <elementGuidId>ca0c25ee-c9cb-479a-bca6-ad014236d1d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-73225-option-2']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-73225-option-2 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>82180a96-92ff-4b00-bf8f-64bb0f63fc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>110201      Bank</value>
      <webElementGuid>756bfffb-4f95-4def-b065-9636007c6719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-73225-option-2&quot;)/span[1]</value>
      <webElementGuid>31e70b73-3fe4-4a8b-9771-adf08fd5d88d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mui-73225-option-2']/span</value>
      <webElementGuid>2ade9895-693c-43fd-b9af-0e3479f0d10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank'])[1]/following::span[1]</value>
      <webElementGuid>0050c70c-c443-488b-a1bd-35ad37ebba6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kas2'])[1]/following::span[1]</value>
      <webElementGuid>7b3747ee-5e25-44ef-a8a1-cab4e0d3f23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank BCA'])[1]/preceding::span[2]</value>
      <webElementGuid>471c923f-126d-459e-8f4b-3d170ced7b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='110201']/parent::*</value>
      <webElementGuid>6ba95084-6b4f-48c9-8546-b8b316f91b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/span</value>
      <webElementGuid>138919c4-92e2-422c-a8fe-23a71d4aeed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '110201      Bank' or . = '110201      Bank')]</value>
      <webElementGuid>f67758d7-234c-4055-afac-8e543369d41b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
