<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Zico</name>
   <tag></tag>
   <elementGuidId>6e9c8943-268c-404f-8b4b-ba5a3845d658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss190.w-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-47593-option-1']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9a5795a0-d75b-48d2-ae9e-288a978d72dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root jss190 w-100</value>
      <webElementGuid>6881033b-90e1-4898-9c2e-4f6efe7a1e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zico</value>
      <webElementGuid>e6460a3c-0de4-423e-b963-bcca1a3f6fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-47593-option-1&quot;)/div[@class=&quot;MuiBox-root jss190 w-100&quot;]</value>
      <webElementGuid>15439815-5223-4cdb-9ceb-330d9c691b86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mui-47593-option-1']/div</value>
      <webElementGuid>04374a8a-38cc-44cf-b549-a1a0f60c1321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Kontak'])[1]/following::div[1]</value>
      <webElementGuid>6a57799a-be68-4ac0-83ab-14a295e5ff42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[10]</value>
      <webElementGuid>eb23aa06-70e5-4e2e-99f5-d1e3ce202820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kim Jong Unch'])[1]/preceding::div[2]</value>
      <webElementGuid>23c7bad1-4196-40ef-bcd2-3f3c095fdbb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li[2]/div</value>
      <webElementGuid>8c9d88e7-f4ad-4390-afef-ca2a2a554d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Zico' or . = 'Zico')]</value>
      <webElementGuid>204332d0-f4df-47ba-b66a-4a2f73ab6b9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
