<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Jawir</name>
   <tag></tag>
   <elementGuidId>921bf0eb-55d0-482d-b9f0-81b13848a5b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss194.w-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-86767-option-3']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c38a2c6d-84d6-472b-aa4a-392f1e0ddeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root jss194 w-100</value>
      <webElementGuid>068a7995-59d2-45b9-88ed-ce371710774f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jawir</value>
      <webElementGuid>8229533e-5576-48dc-8fca-f8311943988b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-86767-option-3&quot;)/div[@class=&quot;MuiBox-root jss194 w-100&quot;]</value>
      <webElementGuid>7046cbcd-6dfe-499b-9b11-2a0a8902d05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>99b43d1d-0360-4586-9fcd-0a01078df78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root jss194 w-100</value>
      <webElementGuid>db373edb-1593-4178-907e-f6fea379ab6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jawir</value>
      <webElementGuid>5670d268-9173-4a55-81b0-aad1c3aba6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-88670-option-3&quot;)/div[@class=&quot;MuiBox-root jss194 w-100&quot;]</value>
      <webElementGuid>f99dcb8d-1c07-44aa-87a7-d2da961b95e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mui-86767-option-3']/div</value>
      <webElementGuid>7d9b03a7-03b9-4af0-bc1d-67d3c05c16ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kim Jong Unch'])[1]/following::div[2]</value>
      <webElementGuid>d153c4a4-3981-4dae-94bf-047edad4f0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zico'])[1]/following::div[4]</value>
      <webElementGuid>1a9391dd-a7c7-450a-9874-8c5e6267a167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li[4]/div</value>
      <webElementGuid>52c35a23-94c9-496e-af54-26c0b4fece03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Jawir' or . = 'Jawir')]</value>
      <webElementGuid>68641a01-7166-47ed-8b59-727449746baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mui-88670-option-3']/div</value>
      <webElementGuid>13760780-5b07-4177-99c4-4b2656f4ff01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
