<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Jawir</name>
   <tag></tag>
   <elementGuidId>752cd0b5-8cef-4410-8597-ebf232c7be1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss194.w-100 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-86767-option-3']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c42820b2-2268-46a4-8f45-7e1f4593790f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jawir</value>
      <webElementGuid>23bb3387-108d-4bc6-8e69-4ff8a86371f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-86767-option-3&quot;)/div[@class=&quot;MuiBox-root jss194 w-100&quot;]/span[1]</value>
      <webElementGuid>f9c73cec-c959-464c-8109-9fc717b0eaf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mui-86767-option-3']/div/span</value>
      <webElementGuid>ead6d2d7-ada7-42d9-a19b-1f1b1cdf921f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kim Jong Unch'])[1]/following::span[7]</value>
      <webElementGuid>2d8f10de-4efa-44ad-bd49-7f48f9ac2fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zico'])[1]/following::span[14]</value>
      <webElementGuid>aeceb363-db44-4639-8b77-9e551a9270a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jawir']/parent::*</value>
      <webElementGuid>32d4ab64-c467-46cf-9afd-b6c8012d6240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li[4]/div/span</value>
      <webElementGuid>9c421018-7b53-42df-b28d-9bd94b6d2781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Jawir' or . = 'Jawir')]</value>
      <webElementGuid>0eb91680-e1f0-4af4-9015-b8b7e1557362</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
