<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_39d8b93e-d3aa-4abb-995c-5a076dcc6f9d</name>
   <tag></tag>
   <elementGuidId>a6fbbcc2-75dd-464a-a36c-28e4e1346783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='39d8b93e-d3aa-4abb-995c-5a076dcc6f9d']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;39d8b93e-d3aa-4abb-995c-5a076dcc6f9d&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e70d156-0ee5-4459-a803-932d01ed0cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss51</value>
      <webElementGuid>d6c3db05-4cfa-4e7c-8ac5-7b7b02c7e1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>39d8b93e-d3aa-4abb-995c-5a076dcc6f9d</value>
      <webElementGuid>bc31fa47-efe9-448b-b1c1-24ae773a9e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8193fb8d-a635-4186-8b23-d2e6628ab2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6136f7c7-e330-4812-8959-c3c49553219c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiGrid-root auth MuiGrid-container&quot;]/div[@class=&quot;MuiGrid-root right-side MuiGrid-item MuiGrid-grid-xs-9 MuiGrid-grid-md-10&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;MuiBox-root jss45 contact-content&quot;]/div[@class=&quot;MuiGrid-root list_body__2zojW margin-top-4 MuiGrid-container MuiGrid-direction-xs-column&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-item MuiGrid-grid-xs-12&quot;]/div[@class=&quot;DataTable_root__2GacI&quot;]/table[1]/tbody[1]/tr[@class=&quot;pointer  tr_custom&quot;]/td[1]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss48 MuiCheckbox-root MuiCheckbox-colorPrimary MuiIconButton-colorPrimary&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss51&quot;]</value>
      <webElementGuid>d11c0e65-a430-4690-9b38-68a859559bb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='39d8b93e-d3aa-4abb-995c-5a076dcc6f9d']</value>
      <webElementGuid>badb52c1-b222-4983-9784-5b222e848c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div[2]/div[2]/div/table/tbody/tr[2]/td/span/span/input</value>
      <webElementGuid>c3c62ead-d1f7-4534-9fe7-d2ed6f3e3c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/span/span/input</value>
      <webElementGuid>85684232-a9c4-414a-874f-5c2b4c074378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = '39d8b93e-d3aa-4abb-995c-5a076dcc6f9d' and @type = 'checkbox']</value>
      <webElementGuid>f70d4d5b-1736-42e9-9342-9231c87833a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
