<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gadget</name>
   <tag></tag>
   <elementGuidId>ddc3fa83-63f7-4327-9c25-572e6f43d655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-81324-option-3']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss74.w-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76dd536f-e66f-4690-929c-92bb372be997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root jss74 w-100</value>
      <webElementGuid>d550fb28-51d3-466f-b526-3861d5c3e55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gadget</value>
      <webElementGuid>126b2485-2b21-4b7b-bfe7-860e92239ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-81324-option-3&quot;)/div[@class=&quot;MuiBox-root jss74 w-100&quot;]</value>
      <webElementGuid>b7fd9dd1-a298-497a-8873-47679f40e18e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mui-81324-option-3']/div</value>
      <webElementGuid>f711becf-ca11-421b-a43b-6f61f3f6ed0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elektronik'])[1]/following::div[1]</value>
      <webElementGuid>bdc43096-88fe-481d-9529-90ad0c52475a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barang Umum'])[3]/following::div[2]</value>
      <webElementGuid>a8f3cea9-f07f-4f5c-a463-daa342bd8301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/ul/li[4]/div</value>
      <webElementGuid>53a3c363-8cb2-4764-a5ee-bc449e55aef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Gadget' or . = 'Gadget')]</value>
      <webElementGuid>7953efa3-7aea-490f-961a-678355c42875</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
