<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Unit_kakutor-dotcircle</name>
   <tag></tag>
   <elementGuidId>50ead682-ec86-41e2-9a3f-218895a85679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div[3]/div[3]/div/table/tbody/tr/td[9]/button/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.kakutor-dotcircle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4934f29b-d26d-429b-ab1c-3c900f8ff641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kakutor-dotcircle</value>
      <webElementGuid>6b11fb58-7728-4e7d-8399-701006e2dd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiGrid-root auth MuiGrid-container&quot;]/div[@class=&quot;MuiGrid-root right-side MuiGrid-item MuiGrid-grid-xs-9 MuiGrid-grid-md-10&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;MuiBox-root jss45 inventory-content&quot;]/div[@class=&quot;MuiGrid-root list_body__2qRPa margin-top-4 MuiGrid-container MuiGrid-direction-xs-column&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-item MuiGrid-grid-xs-12&quot;]/div[@class=&quot;DataTable_root__2GacI&quot;]/table[1]/tbody[1]/tr[@class=&quot;pointer  tr_custom&quot;]/td[9]/button[@class=&quot;MuiButtonBase-root MuiIconButton-root Icon_button__1ikrc&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/i[@class=&quot;kakutor-dotcircle&quot;]</value>
      <webElementGuid>f9248ad0-5f9e-4710-9c63-fba4bda63076</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div[3]/div[3]/div/table/tbody/tr/td[9]/button/span/i</value>
      <webElementGuid>f5b2b15d-7cd4-4827-8f7f-517351426653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/button/span/i</value>
      <webElementGuid>b3de9ded-4e2c-4ed6-a8ca-27b3acb10927</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
