<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Barang</name>
   <tag></tag>
   <elementGuidId>3d632ff4-fb96-423d-97e6-0410793b518a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/ul/li[7]/div/div/ul/li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Barang' or . = 'Barang')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.MuiListItem-root.lists__item.nested.pointer.MuiListItem-gutters</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9e7e544c-acd5-4252-83e5-4cc3d3e0f7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiListItem-root lists__item nested pointer MuiListItem-gutters</value>
      <webElementGuid>76b1ace8-b079-4361-9105-f25f231c4b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Barang</value>
      <webElementGuid>d9a77b27-0a7d-480c-bdee-19f192a7ecc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiGrid-root auth MuiGrid-container&quot;]/div[@class=&quot;MuiGrid-root left-side MuiGrid-item MuiGrid-grid-xs-3 MuiGrid-grid-md-2&quot;]/div[@class=&quot;fixed-menu&quot;]/ul[@class=&quot;MuiList-root lists MuiList-padding&quot;]/li[@class=&quot;MuiCollapse-container MuiCollapse-entered&quot;]/div[@class=&quot;MuiCollapse-wrapper&quot;]/div[@class=&quot;MuiCollapse-wrapperInner&quot;]/ul[@class=&quot;MuiList-root MuiList-padding&quot;]/li[@class=&quot;MuiListItem-root lists__item nested pointer MuiListItem-gutters&quot;]</value>
      <webElementGuid>3d13c62c-7310-45ce-ad13-3db45f12e314</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/ul/li[7]/div/div/ul/li</value>
      <webElementGuid>e7f77678-ce1a-439d-8590-c1854dbff4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jasa'])[1]/preceding::li[1]</value>
      <webElementGuid>1d048044-c06a-49a8-930c-8d9ac63923a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/div/ul/li</value>
      <webElementGuid>8e23aefc-dab0-4cc1-af62-2fdd10a8b3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Barang' or . = 'Barang')]</value>
      <webElementGuid>64c356a1-e15c-4ad2-82d5-3ab0fa70d990</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
