<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Gadget</name>
   <tag></tag>
   <elementGuidId>6584690c-b3bb-4056-bd8c-130fb24014a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-96343-option-3']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss83.w-100 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e9c1615-5349-4190-9a26-b19e842c9884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gadget</value>
      <webElementGuid>b96c123b-1ab2-4d9c-a59c-8086c3e0afa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-96343-option-3&quot;)/div[@class=&quot;MuiBox-root jss83 w-100&quot;]/span[1]</value>
      <webElementGuid>76128b9a-331d-4259-beba-6961be9a667b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mui-96343-option-3']/div/span</value>
      <webElementGuid>649acbd5-b08b-41b5-96b1-7eb6b787b3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elektronik'])[1]/following::span[1]</value>
      <webElementGuid>485aeabd-dc6d-45be-a2c3-af3f0ea21e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barang Umum'])[3]/following::span[2]</value>
      <webElementGuid>723ba15f-8123-4a4e-bc9d-f4360130f92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/span</value>
      <webElementGuid>e6a00b64-5e43-481b-828d-dee925d3ab8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Gadget' or . = 'Gadget')]</value>
      <webElementGuid>0386fc8e-1028-4516-88bc-6ccc9c164276</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
